### ISSUE TITLE
eot working in IE8 not in IE7

### ISSUE THREAD

**Issue by AlexandreBroudin** [nfroidure/gulp-iconfont#29]
I have a weird behavior when EOT is generated, it works in IE8 but not in IE7 even with the zoom expression.

for exemple: 

``` css
.lt-ie8 {

.<%= className %> {
    &:before { content: none !important }
}

<% _.each(glyphs, function(glyph) { %>
  .<%= className %>-<%= glyph.name %> {zoom: expression( this.runtimeStyle['zoom'] = '1', this.innerHTML = '&#x<%= glyph.codepoint.toString(16) %>;')
  }
<% }); %>

}
```

and this is what is generated

``` css
  .lt-ie8 .icon:before {
    content: none !important;
  }
 .lt-ie8 .icon-check {
    zoom: expression( this.runtimeStyle['zoom'] = '1', this.innerHTML = '&#xe00a;')
  }
```

the font is correctly imported 

``` css
@font-face {
  font-family: "<%= fontName %>";
  src: url('<%= fontPath %><%= fontName %>.eot');
  src: url('<%= fontPath %><%= fontName %>.eot?#iefix') format('eot');
}
```

I just have squares like the font is not imported but actually is.
